name: Ruby

on:
  pull_request:
  
    branches:    
      - main
      - de
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Install dependencies
        run: bundle install
        
      - name: Run Rubocop
        continue-on-error: true
        run: bundle exec rubocop

      - name: Run Tests
        run: bundle exec rspec spec
      
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./coverage
