name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

#       - name: Run Rubocop
#         run: bundle exec rubocop

      - name: Run Tests
        run: rails test
